name: Java CI with Gradle

on:
  push:
    branches: [ "**/*" ]
  pull_request:
    branches: [ "**/*" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Environment (PR)
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.event.pull_request.head.sha }})
          version=$(cat gradle.properties | grep mod_version= | sed s/mod_version=//g)
          echo "LAST_COMMIT_SHA=$calculatedSha" >> ${GITHUB_ENV}
          echo "VERSION=$version" >> ${GITHUB_ENV}
      - name: Setup Environment (Push)
        if: ${{ github.event_name == 'push' }}
        shell: bash
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          version=$(cat gradle.properties | grep mod_version= | sed s/mod_version=//g)
          echo "LAST_COMMIT_SHA=$calculatedSha" >> ${GITHUB_ENV}
          echo "VERSION=$version" >> ${GITHUB_ENV}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: gradle build

      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: fantasy-v${{ env.VERSION }}-${{ env.LAST_COMMIT_SHA }}
          path: |
            build/libs/*.jar
            !build/libs/*-sources.jar
